const CREATE_STATUS = 201;
const BAD_REQUEST_ERROR_STATUS = 400;
const UNAUTHORIZED_ERROR_STATUS = 401;
const FORBIDDEN_ERROR_STATUS = 403;
const NOT_FOUND_ERROR_STATUS = 404;
const CONFLICT_ERROR_STATUS = 409;
const INTERNAL_SERVER_ERROR_STATUS = 500;

module.exports = {
  CREATE_STATUS,
  BAD_REQUEST_ERROR_STATUS,
  FORBIDDEN_ERROR_STATUS,
  NOT_FOUND_ERROR_STATUS,
  UNAUTHORIZED_ERROR_STATUS,
  CONFLICT_ERROR_STATUS,
  INTERNAL_SERVER_ERROR_STATUS,
};
